*** Variables ***
${train_page_loc}  //span[text()='Train tickets']
${train_loc}  //span[text()='Cdg Udz Sf Exp']
${from_srch}  //div[text()='From']
${tatkal_button}  (//div[text()='Tatkal'])[1]
${check_train}  //span[text()='Jp Udz Exp']
${tom_train}  //button[text()='Tomorrow']
${price_tatkal}  (//span[@class='fare___fa8948'])[1]
${nxt_date}  //button[text()='Day After']
${normal_price}  (//span[@class="fare___fa8948"])[1]
${srch_but}  (//button[text()='Search Trains'])[1]